# Generated by Django 4.1.7 on 2023-03-08 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='size',
            field=models.IntegerField(default=55, null=True),
        ),
    ]
